#ifndef TEMPLATE_HPP
#define TEMPLATE_HPP

#include <string>

const std::string cmake_content = R"(cmake_minimum_required(VERSION 3.10)

project(MyProject)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED True)

file(GLOB_RECURSE SOURCES "src/*.cpp" "src/*.c")

add_executable(main ${SOURCES})
)";

const std::string main_cpp_content = R"(#include <iostream>

int main() {
    std::cout << "Hello from main.cpp!" << std::endl;
    return 0;
}
)";

const std::string readme_content = R"(# Build directory

This folder contains build files generated by CMake.
)";

const std::string gitignore_content = R"(build)";

#endif
